configServiceAddress:
  ip: 127.0.0.1
  port: 9001
grpcOuterAddress:
  #ip: 127.0.0.1
  port: 9005
grpcInnerAddress:
  ip: 0.0.0.0
  port: 9005
moduleName: isp-system-service

infraServerPort: 9555

logfile:
  path: /var/log/isp-system-service/runtime.log
  maxSizeMb: 512
  maxBackups: 4
  compress: true
