configServiceAddress:
  ip: 127.0.0.1
  port: 9001
grpcOuterAddress:
  #ip: 127.0.0.1
  port: 9005
grpcInnerAddress:
  ip: 0.0.0.0
  port: 9005
moduleName: isp-system-service
instanceUuid: 3f4faf30-8482-48ef-931a-b15575a3af1d

logfile:
  path: /var/log/isp-system-service/runtime.log
  maxSizeMb: 512
  maxBackups: 4
  compress: true
