// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2020-09-21 17:04:25.146581 +0300 MSK m=+89.051194375

package docs

import (
	"github.com/integration-system/isp-lib/v2/docs"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "GNU GPL v3.0"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/access_list/get_by_id": {
            "post": {
                "description": "Возвращает список методов для приложения, для которых заданы настройки доступа",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accessList"
                ],
                "summary": "Получить список доступности методов для приложения",
                "parameters": [
                    {
                        "description": "идентификатор приложения",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/domain.Identity"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "список доступности методов",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.MethodInfo"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    }
                }
            }
        },
        "/access_list/set_list": {
            "post": {
                "description": "Возвращает список методов для приложения, для которых заданы настройки доступа",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accessList"
                ],
                "summary": "Настройть доступность списка методов для приложения",
                "parameters": [
                    {
                        "description": "объект настройки доступа",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/domain.SetListRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "список доступности методов",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.MethodInfo"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    }
                }
            }
        },
        "/access_list/set_one": {
            "post": {
                "description": "Возвращает количество изменных строк",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accessList"
                ],
                "summary": "Настроить доступность метода для приложения",
                "parameters": [
                    {
                        "description": "объект для настройки доступа",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/entity.AccessList"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "количество измененных строк",
                        "schema": {
                            "$ref": "#/definitions/domain.CountResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    }
                }
            }
        },
        "/application/create_update_application": {
            "post": {
                "description": "Если приложение с такими идентификатором существует, то обновляет данные, если нет, то добавляет данные в базу",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "application"
                ],
                "summary": "Создать/обновить приложение",
                "parameters": [
                    {
                        "description": "Объект приложения",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Application"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.AppWithToken"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    }
                }
            }
        },
        "/application/delete_applications": {
            "post": {
                "description": "Удаляет приложения по списку их идентификаторов, возвращает количество удаленных приложений",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "application"
                ],
                "summary": "Удалить приложения",
                "parameters": [
                    {
                        "description": "Массив идентификаторов приложений",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.DeleteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    }
                }
            }
        },
        "/application/get_application_by_id": {
            "post": {
                "description": "Возвращает описание приложения по его идентификатору",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "application"
                ],
                "summary": "Получить приложение по идентификатору",
                "parameters": [
                    {
                        "description": "Идентификатор приложения",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Identity"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.AppWithToken"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    }
                }
            }
        },
        "/application/get_applications": {
            "post": {
                "description": "Возвращает массив приложений с токенами по их идентификаторам",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "application"
                ],
                "summary": "Получить список приложений",
                "parameters": [
                    {
                        "description": "Массив идентификаторов приложений",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.AppWithToken"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    }
                }
            }
        },
        "/application/get_applications_by_service_id": {
            "post": {
                "description": "Возвращает список приложений по запрошенныму идентификатору сервиса",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "application"
                ],
                "summary": "Получить список приложений по идентификатору сервиса",
                "parameters": [
                    {
                        "description": "Идентификатор серсиса",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Identity"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.AppWithToken"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    }
                }
            }
        },
        "/application/get_system_tree": {
            "post": {
                "description": "Возвращает описание взаимосвязей сервисов и приложений",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "application"
                ],
                "summary": "Метод получения системного дерева",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.DomainWithServices"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    }
                }
            }
        },
        "/domain/create_update_domain": {
            "post": {
                "description": "Если домен с такими идентификатором существует, то обновляет данные, если нет, то добавляет данные в базу",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "domain"
                ],
                "summary": "Создать/обновить домен",
                "parameters": [
                    {
                        "description": "Объект домена",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Domain"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Domain"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    }
                }
            }
        },
        "/domain/delete_domains": {
            "post": {
                "description": "Удаляет домены по списку их идентификаторов, возвращает количество удаленных доменов",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "domain"
                ],
                "summary": "Удаление доменов",
                "parameters": [
                    {
                        "description": "Массив идентификаторов доменов",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.DeleteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    }
                }
            }
        },
        "/domain/get_domain_by_id": {
            "post": {
                "description": "Возвращает описание домена по его идентификатору",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "domain"
                ],
                "summary": "Получить домен по идентификатору",
                "parameters": [
                    {
                        "description": "Идентификатор домена",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Identity"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Domain"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    }
                }
            }
        },
        "/domain/get_domains_by_system_id": {
            "post": {
                "description": "Возвращает список доменов по системному идентификатору",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "domain"
                ],
                "summary": "Получить домены по идентификатору системы",
                "parameters": [
                    {
                        "description": "Идентификатор системы",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity.Domain"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    }
                }
            }
        },
        "/service/create_update_service": {
            "post": {
                "description": "Если сервис с такими идентификатором существует, то обновляет данные, если нет, то добавляет данные в базу",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service"
                ],
                "summary": "Создать/обновить сервис",
                "parameters": [
                    {
                        "description": "Объект сервиса",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Service"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Service"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    }
                }
            }
        },
        "/service/delete_service": {
            "post": {
                "description": "Удаляет сервисов по списку их идентификаторов, возвращает количество удаленных сервисов",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service"
                ],
                "summary": "Удалить сервисы",
                "parameters": [
                    {
                        "description": "Массив идентификаторов сервисов",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.DeleteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    }
                }
            }
        },
        "/service/get_service": {
            "post": {
                "description": "Возвращает список сервисов по их идентификаторам",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service"
                ],
                "summary": "Получить список сервисов",
                "parameters": [
                    {
                        "description": "Массив идентификаторов сервисов",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity.Service"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    }
                }
            }
        },
        "/service/get_service_by_id": {
            "post": {
                "description": "Возвращает описание сервиса по его идентификатору",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service"
                ],
                "summary": "Получить сервис по идентификатору",
                "parameters": [
                    {
                        "description": "Идентификатор сервиса",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Identity"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Service"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    }
                }
            }
        },
        "/service/get_services_by_domain_id": {
            "post": {
                "description": "Возвращает список сервисов по идентификатору домена",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service"
                ],
                "summary": "Получить список сервисов по идентификатору домена",
                "parameters": [
                    {
                        "description": "Идентификатор домена",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Identity"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity.Service"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    }
                }
            }
        },
        "/system/create_update_system": {
            "post": {
                "description": "Если система с такими идентификатором существует, то обновляет данные, если нет, то добавляет данные в базу",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Создать/обновить систему",
                "parameters": [
                    {
                        "description": "Объект системы",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.System"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.System"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    }
                }
            }
        },
        "/system/delete_systems": {
            "post": {
                "description": "Удаляет системы по списку их идентификаторов, возвращает количество удаленных систем",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Удалить системы",
                "parameters": [
                    {
                        "description": "Массив идентификаторов систем",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.DeleteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    }
                }
            }
        },
        "/system/get_system_by_id": {
            "post": {
                "description": "Возвращает описание системы по ее идентификатору",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Получить систему по идентификатору",
                "parameters": [
                    {
                        "description": "Идентификатор системы",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Identity"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.System"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    }
                }
            }
        },
        "/system/get_systems": {
            "post": {
                "description": "Возвращает список систем по их идентификаторам",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Получить список систем",
                "parameters": [
                    {
                        "description": "Массив идентификаторов систем",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity.System"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    }
                }
            }
        },
        "/token/create_token": {
            "post": {
                "description": "Созддает токен и привязывает его к приложению",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "token"
                ],
                "summary": "Создать токен",
                "parameters": [
                    {
                        "description": "Объект создания токена",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.AppWithToken"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    }
                }
            }
        },
        "/token/get_tokens_by_app_id": {
            "post": {
                "description": "Возвращает список токенов, привязанных к приложению",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "token"
                ],
                "summary": "Получить токены по идентификаотру приложения",
                "parameters": [
                    {
                        "description": "Идентификатор приложения",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Identity"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity.Token"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    }
                }
            }
        },
        "/token/revoke_tokens": {
            "post": {
                "description": "Отвязывает токены от приложений и удялет их",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "token"
                ],
                "summary": "Отозвать токены",
                "parameters": [
                    {
                        "description": "Объект отзыва токенов",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.RevokeTokensRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.AppWithToken"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    }
                }
            }
        },
        "/token/revoke_tokens_for_app": {
            "post": {
                "description": "Отвязывает токены от приложений и удаляет их по идентификатору приложения",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "token"
                ],
                "summary": "Отозвать токены для приложения",
                "parameters": [
                    {
                        "description": "Идентификатор приложения",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Identity"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.DeleteResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/structure.GrpcError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.AppWithToken": {
            "type": "object",
            "properties": {
                "app": {
                    "type": "object",
                    "$ref": "#/definitions/entity.Application"
                },
                "tokens": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Token"
                    }
                }
            }
        },
        "domain.CountResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                }
            }
        },
        "domain.CreateTokenRequest": {
            "type": "object",
            "required": [
                "appId"
            ],
            "properties": {
                "appId": {
                    "type": "integer"
                },
                "expireTimeMs": {
                    "type": "integer"
                }
            }
        },
        "domain.DeleteResponse": {
            "type": "object",
            "properties": {
                "deleted": {
                    "type": "integer"
                }
            }
        },
        "domain.DomainWithServices": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "services": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ServiceWithApps"
                    }
                }
            }
        },
        "domain.Identity": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "domain.MethodInfo": {
            "type": "object",
            "properties": {
                "method": {
                    "type": "string"
                },
                "value": {
                    "type": "boolean"
                }
            }
        },
        "domain.RevokeTokensRequest": {
            "type": "object",
            "required": [
                "appId"
            ],
            "properties": {
                "appId": {
                    "type": "integer"
                },
                "tokens": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "domain.ServiceWithApps": {
            "type": "object",
            "properties": {
                "apps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.SimpleApp"
                    }
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "domain.SetListRequest": {
            "type": "object",
            "properties": {
                "appId": {
                    "type": "integer"
                },
                "methods": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.MethodInfo"
                    }
                },
                "removeOld": {
                    "type": "boolean"
                }
            }
        },
        "domain.SimpleApp": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "tokens": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Token"
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "entity.AccessList": {
            "type": "object",
            "properties": {
                "appId": {
                    "type": "integer"
                },
                "method": {
                    "type": "string"
                },
                "value": {
                    "type": "boolean"
                }
            }
        },
        "entity.Application": {
            "type": "object",
            "required": [
                "name",
                "serviceId",
                "type"
            ],
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "serviceId": {
                    "type": "integer"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "SYSTEM",
                        "MOBILE"
                    ]
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "entity.Domain": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "systemId": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "entity.Service": {
            "type": "object",
            "required": [
                "domainId",
                "name"
            ],
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "domainId": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "entity.System": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "entity.Token": {
            "type": "object",
            "required": [
                "appId",
                "token"
            ],
            "properties": {
                "appId": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "expireTime": {
                    "type": "integer"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "structure.GrpcError": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "array",
                    "items": {
                        "type": "object"
                    }
                },
                "errorCode": {
                    "type": "string"
                },
                "errorMessage": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = docs.SwaggerInfo{
	Version:     "1.1.2",
	Host:        "localhost:9003",
	BasePath:    "/api/system",
	Schemes:     []string{},
	Title:       "ISP system service",
	Description: "Сервис управления реестром внешних приложений и токенами аутентификации",
}

func init() {
	docs.InitSwagger(SwaggerInfo, doc)
}
